dist: trusty
sudo: required
env:
  - TRAVIS=true
language: node_js
node_js:
    - "node"
    - "lts/*"
    - "9"
before_install:
    - npm install -g npm@latest
    - npm install -g eye.js
install:
    - npm install
script:
    - eye
